#######################
####--ALUMNO--##########
#######################
@api =  http://localhost:3000/alumno

##POST
###Insertar 1 alumno
POST {{api}}
Content-Type: application/json

{
    "nombre_usuario": "alumnoPrueba",
    "contraseña": "1234",
    "permisos": "2",
    "correo_electronico": "test@test.com",
    "correo_electronico_profesor": "nuevesito@hotmail.es",
    "imagen": "default.jpg"
}

## GET 
###1 alumno por id
GET {{api}}/alum_3

###COUNT alumno
GET {{api}}/count

###GET all alumno
GET {{api}}

##PUT
###
PUT {{api}}/alum_2
Content-Type: application/json 

{
    "nombre_usuario": "amoPUT",
    "correo_electronico": "alumnoPUT_rreo"
}

##DELETE
###
DELETE {{api}}/alum_2

##POST
###Asignar tarea a alumno
POST {{api}}/asignar_tarea
Content-Type: application/json

{
    "id_alumno": "3",
    "id_tarea": "task_1",
    "fecha": "22-12-2009",
    "hora": "22:12:20"
}