@api =  http://localhost:3000/multimedia

## POST
### Crea un inventario
POST {{api}}
Content-Type: application/json

{
    "tareaId": "task_1",
    "paso": "1",
    "descripcion": "Ir a la cocina",
    "urlFoto": "../images/ir.png"

}

### Obtener cantidad multimedia
GET {{api}}/count

### Obtener url de multimedia por id de tarea
POST  {{api}}/task_1
Content-Type: application/json

{
    "paso": "1"
}


### Obtener cantidad multimedia
GET {{api}}/pasos/task_1
