@api =  http://localhost:3000/objetos

## POST
### Crea un inventario
POST {{api}}
Content-Type: application/json

{
    "inventarioId": "inventario4",
    "nombre": "libreta",
    "cantidad": "50",
    "categoria": "Material donde escribir"
}

##GET
### Obtener todos los objetos
GET {{api}}
### Obtener cantidad inventarios
GET {{api}}/count
### Obtener inventario por id
GET {{api}}/objeto2

##UPDATE
### Cambiar un inventario dado un id
PUT {{api}}/objeto2
Content-Type: application/json

{
    "id_inventario_inObjeto": "inventario2",
    "nombre_objeto": "Tiza",
    "cantidad_objetos": "30",
    "categoria": "material pizarra"
}

##DELETE
### Eliminar un inventario dado un id
DELETE {{api}}/objeto2
