#######################
####--Tarea--##########
#######################
@api =  http://localhost:3000/tarea

##POST
###Insertar 1 tarea nueva
POST {{api}}
Content-Type: application/json

{
    "id_alumno": "alum_3",
    "tipo": "Poner Microondas",
    "tiempo_requerido": "02:00:00",
    "fecha": "2021-11-30",
    "hora": "23:59:00",
    "tipo_multimedia": "Imagen"
}

### Asignar tarea
POST {{api}}/asignar
Content-Type: application/json

{
    "nombreUsuario": "alumnoPOST2",
    "tipoTarea": "Poner Microondas"
}

## GET 
###1 Obtener una tarea por id
GET {{api}}/task_1

###COUNT numero de tareas del sistema
GET {{api}}/count

###GET obtener lista de todas las tareas
GET {{api}}

###GET obtener lista de todas las tareas
GET {{api}}/distinct

###GET obtener lista de tareas dadas un alumno
GET {{api}}/list/test@test.com
##PUT
### Actualizar los datos de un profesor
PUT {{api}}/task_2
Content-Type: application/json 

{
    "tipo": "tipo nuevo nuevito",
    "tipo_multimedia": "video"
}


###PUT
### Finalizar una tarea (cambiar estado a finalizado)
PUT {{api}}/state/task_2
Content-Type: application/json 
