@api =  http://localhost:3000



GET {{api}}/usuario
###
GET {{api}}/usuario/2
###
GET {{api}}/usuario/count
###
POST {{api}}/usuario
Content-Type: application/json

{
    "title": "I must create an app",
    "description": "Using React Native"
}
###
DELETE {{api}}/usuario/6
###
PUT {{api}}/usuario/4
Content-Type: application/json

{
    "description": "descripcion 3",
    "title": "titulo 3"

}



###
GET {{api}}/usuario/profesor