@api =  http://localhost:3000



GET {{api}}/usuario
###
GET {{api}}/usuario/2
###
GET {{api}}/usuario/count
###
POST {{api}}/usuario
Content-Type: application/json

{
    "nombre_usuario": "prueba7",
    "contraseña": "prueba7",
    "permisos": "0",
    "correo_electronico": "prueba7"

}

###
DELETE {{api}}/usuario/2
###
PUT {{api}}/usuario/1
Content-Type: application/json

{
    "nombre_usuario": "prueba7",
    "contraseña": "prueba7",
    "permisos": "0",
    "correo_electronico": "prueba7"
}
